client/app.js
client/components/nav.js

about page added

---

client/components/About.js
package-lock.json
package.json

added react youtube and centered video on about page

added react-youtube

---

client/components/browse.jsx
client/utilities.js

Fixed some issues with the filter utility

fixed browse utility

---

.eslintrc.js
.prettierignore
client/app.jsx
client/components/browse.jsx
client/components/login.jsx
client/components/nav.jsx
client/components/search.jsx
client/redux/rootReducer.js
client/redux/users/actions.js
client/redux/users/reducer.js
client/redux/users/types.js
package-lock.json
package.json
seed.js
server/api/index.js
server/api/routers/movies.js
server/api/routers/users.js
server/db/Models/Session.js
server/db/Models/User.js
server/db/Models/index.js

fixed all lint issues on authentication (still need to salt/hash)

Authentication

---

.eslintrc.js
client/components/search.jsx
client/components/singleMovieBox.jsx
client/utilities.js

Shrutisearch

---

client/components/browse.jsx
client/components/moviePage.jsx

Fixed the genre sorting (things were happening out of order in componentDidMount() after adjusting for airbnb).  Fixed another propType error on moviePage.

fixed filter and some linting errors

---

client/app.jsx
client/components/browse.jsx
client/components/search.jsx
client/components/singleMovieBox.jsx
seed.js
server/db/Models/Cart.js
server/db/Models/index.js

Used a string method to initiate an array for Cart's property "items". Made association of Cart.BelongsTo(Sessions)
SingleMovieBox now contains quantity

added Cart Model and quantity to SingleMovieBox

---

README.md
server/db/Models/Cart.js
server/db/Models/Order.js
server/db/Models/index.js

added orders model and updated relations on models index.
you may need to delete the tables in postico and then run start:server in order to see the changes reflecting in postico

db models and readme updated

---

client/components/cart.jsx
client/components/singleMovieBox.jsx
client/redux/cart/actions.js
client/redux/cart/reducer.js
client/redux/cart/types.js
client/redux/movies/actions.js
client/redux/rootReducer.js
server/api/index.js
server/api/routers/cart.js
server/api/routers/index.js
server/api/routers/users.js
server/db/Models/Cart.js

cart works

---

client/app.jsx
client/components/search.jsx

PR has changes for codeReview comments

codeReviewChange

---

client/components/cart.jsx
client/redux/cart/actions.js
package-lock.json
package.json
public/index.html
server/api/index.js
server/api/routers/cart.js
server/db/Models/Order.js

stripe integrated!! Team was present 👯

changes for stripe integration

---

client/components/cart.jsx
client/redux/cart/actions.js

Shows total
Changed background so that the numbers show

total added to cart.js

---

client/components/search.jsx
client/utilities.js

Modified search to work on onChange and removed button ..Made UI similar to other pages

search onchange and look and feel changes

---

client/components/admin.jsx
server/api/routers/cart.js

fixed bug in the admin previous order route that would send back incomplete list of carts, fixed by preventing res.send until every single inactive cart is built out into one of these 'cart objects'

fixed small admin bug

---

client/components/admin.jsx
client/components/cart.jsx
client/components/moviePage.jsx
client/components/singleMovieBox.jsx
client/redux/cart/actions.js
client/utilities.js
server/api/routers/cart.js
server/api/routers/movies.js

- admin page bug that Chad ran into is fixed, page no longer crashes
- we have inventory!  add to cart, remove from cart, and edit quantity have been updated to check movie stock and handle accordingly.  inputs have been updated with a max={ movie.stock } as an extra safeguard.  please excuse all of the comments, it looks a little crazy but I tested it rigorously, it works. can answer any questions about it.
- admin page displays a warning banner across the top of the screen letting you know which movies are low in stock (10 or below).  this one does not time out, the admin needs to address the low inventory!
- fixed the bug in the cart that shuffled around orders on quantity change
- fixed bug in admin user section that shuffled around users on admin change
- fixed cart alignment and …

inventory and a few little things

---

client/app.jsx
client/components/index.js
client/components/landingPage.jsx
client/pages/index.js
public/styles.css

landingPage added

---

client/components/admin.jsx
client/components/cart.jsx
client/components/moviePage.jsx
client/components/singleMovieBox.jsx
client/redux/cart/actions.js
client/redux/cart/reducer.js
server/db/Models/Movie.js

revamped our currency handling, did this as a group

fixed money

---

client/components/userAccount.jsx

utilized same logic from admin side to view previous orders, but filtered on the current logged in user

added in users past orders

---

client/components/admin.jsx
client/components/browse.jsx
client/components/cart.jsx
client/components/login.jsx
client/components/logoutPage.jsx
client/components/moviePage.jsx
client/components/nav.jsx
client/components/search.jsx
client/components/signup.jsx
client/components/singleMovieBox.jsx
client/redux/cart/actions.js
client/redux/movies/actions.js
client/redux/users/actions.js
server/api/routers/cart.js
server/api/routers/movies.js
server/api/routers/users.js

- all sorts of styling fixes for consistency (input styling, buttons in places we missed, alerts replaced with toasts) and just general things to make it look a little more sleek 
- added error handling if admin tries to add movie to the database that's already in the database
- added error handling so there's a toast notification for wrong password
- 'username already in use' now displays in red on the signup page
- started deleting console.logs/commented out code
- removed add to wishlist (maybe someday...)
- admin previous orders now sorted by date order
- checkout re-directs to browse instead of home (get them buying more movies!)

style and other fixes

---

client/components/about.jsx
client/components/cart.jsx
client/components/landingPage.jsx
client/components/login.jsx
client/components/logoutPage.jsx
client/components/moviePage.jsx
client/components/search.jsx
client/components/signup.jsx
client/components/singleMovieBox.jsx
client/components/userAccount.jsx
client/redux/cart/actions.js
client/redux/movies/reducer.js
client/redux/users/actions.js
public/index.html
public/styles.css
seed.js
server/api/index.js
server/api/routers/cart.js
server/api/routers/movies.js

fixed a few little css things, api security, removed comments/console.logs

remove comments, landing animation
